### ISSUE TITLE
Problem with getting logout to work properly

### ISSUE THREAD

**Issue by LalaDK** [sportngin/saml_idp#56]
I'm having difficulties with implementing the logout functionality of your otherwise awesome IDP.

Currently the result of calling the IDP#logout action with SP SLO object results in this error:
undefined method `authn_request?' for nil:NilClass at the method "encode_response":

def idp_make_saml_response(found_user)
    encode_response found_user
end

I've tried to put in a debugger to get a look at what's going on, and currently I'm confused how come the before_filter "before_filter :validate_saml_request, only: [:new, :create]" in saml_idp/app/controllers/saml_idp/idp_controller.rb should not be applied for the logout action as well. 

As far as I see, the method 'validate_saml_request' is the only one which calls 'decode_request' in saml_idp/app/controllers/saml_idp/idp_controller.rb which results in setting self.saml_request. 
And it seems like the method "encode_response" depends on it being set. 

Currently my method "idp_logout" is plain empty, but I don't think that should be a problem, should it?

Thank you in advance.

**Comment by mvastola** [comment]
@LalaDK, I think you're right about `validate_saml_request` applying to the logout action.
FWIW, if you attempted this now, `saml_response` *would* be set per [this code](https://github.com/sportngin/saml_idp/blame/e1f8fa5324aee8c79258a2c6dc71df6a69acfe01/lib/saml_idp/controller.rb#L20) which was committed after this issue, but without applying the `before_filter` the request would be considered an authentication request.

The `idp_logout` theoretically can be empty if the IdP only does authentication and doesn't store a session with the user being logged in. Otherwise the `idp_logout` should destroy the current session (or at least log the user out).
